# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuoteApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'MHNetwork', :path => '~/Desktop/MHNetwork'
  target 'QuoteAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuoteAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
