//
//  QuoteViewController.swift
//  QuoteApp
//
//  Created Mohamed Emad Abdalla Hegab on 17.07.18.
//  Copyright © 2018 Mohamed Hegab. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class QuoteViewController: UIViewController, QuoteViewProtocol {
 
    @IBOutlet weak var authorLabel: UILabel!
    @IBOutlet weak var quoteLabel: UILabel!
    var presenter: QuotePresenterProtocol?

    override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationController?.isNavigationBarHidden = true
        presenter?.getRandomQuote(onComplete: { (quote) in
            self.quoteLabel.text = quote.quote
            self.authorLabel.text = quote.author
        }, onError: { (error) in
            print(error)
        })
    }

}
